[package]
name = 'mcr'
version = "0.0.0"
license = "Apache 2.0"

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
mcr = "_"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
